---
extends: stylelint-config-standard
rules:
  selector-type-no-unknown:
  length-zero-no-unit:
  declaration-empty-line-before:
  color-hex-case: upper
  at-rule-no-unknown:
  at-rule-empty-line-before:
  string-no-newline:
  value-list-max-empty-lines:
  value-list-comma-newline-after:
  function-max-empty-lines:
  number-leading-zero: always
  function-comma-space-after: always
  declaration-colon-space-after: always-single-line
  declaration-colon-newline-after:
  declaration-colon-space-before: never
  no-descending-specificity:
