---
extends: stylelint-config-standard
rules:
  selector-type-no-unknown: null
  length-zero-no-unit: null
  declaration-empty-line-before: null
  color-hex-case: upper
  at-rule-no-unknown: null
  at-rule-empty-line-before: null
  string-no-newline: null
  value-list-max-empty-lines: null
  function-max-empty-lines: null
