name: Louis Orleans' Résumé
short_name: Résumé
description: Louis Orleans' Résumé
start_url: index.html?utm_source=web_app_manifest
display: standalone
background_color: #920000
theme_color: #920000
lang: en-US
icons:
  - src: assets/icon/icon-128.png
    sizes: 128x128
    type: image/png
  - src: assets/icon/icon-192.png
    sizes: 192x192
    type: image/png
  - src: assets/icon/icon-256.png
    sizes: 256x256
    type: image/png
  - src: assets/icon/icon-512.png
    sizes: 512x512
    type: image/png
  - src: assets/icon/icon-1024.png
    sizes: 1024x1024
    type: image/png
